#!/usr/bin/python
import boto.sns
import uuid
import json

# Get hostname
hostname = raw_input("Enter hostname to check: ")

# generate ID
checkId = uuid.uuid4()

# create json message
message = json.dumps({"checkId": str(checkId), "hostname": hostname})

# connect to sns
snsConn = boto.sns.connect_to_region("us-west-2")

# Publish notification
snsConn.publish("arn:aws:sns:us-west-2:738476036662:dnsCheckerFrontend-checkerTopic-PWC4HROXDB1I", message)
